### ISSUE TITLE
Price doesn't update unless using spin button

### ISSUE THREAD

**Issue by cassidyjames** [jeremyvaartjes/subminder#1]
For some reason when I type a price in, it gets reset to `0.00`. However, if I use the spin button, it properly sets the price.

**Comment by jeremyvaartjes** [comment]
Yeah there were some issues with this but had thought I fixed it, will look into it again.

**Comment by jeremyvaartjes** [comment]
Fixed the issue. The value wasn't updating correctly because I was using the "changed" signal and not the "value_changed" signal that is specific to the spinbutton.
