### ISSUE TITLE
Adapt currency symbol depending of chosen currency

### ISSUE THREAD

**Issue by NathanBnm** [jeremyvaartjes/subminder#4]
The currency symbol is actually the Dollar ($) by default, but when I choose Euro (€), the dollar symbol is still displayed instead of the euro symbol.

You should make the symbol change depending of the chosen currency.

**Comment by freaktechnik** [comment]
From what I can tell the actual displayed values also don't change, it always shows the cost in the currency of the actual subscription?

**Comment by jeremyvaartjes** [comment]
Fixed in 1.1.0
I'm showing both the currency of the subscription and the converted value to your default currency if the subscription doesn't use the default currency so it is a bit more clear.
I've also got proper currency symbol support now, not just using $ symbols everywhere.
