### ISSUE TITLE
Add searchbar when adding subscription

### ISSUE THREAD

**Issue by NathanBnm** [jeremyvaartjes/subminder#5]
Maybe you can add a searchbar on the top of the list when you add a new subscription. This will help to find the subscription you're looking for more efficiently. Especially if the list gets bigger.

**Comment by freaktechnik** [comment]
The list has type to find, like finder, so just start typing to start searching in the list.

**Comment by NathanBnm** [comment]
I didn't noticed that, maybe it can still be a good idea to add a searchbar. People don't always know that.

**Comment by jeremyvaartjes** [comment]
The list is now sorted and there is a search bar so it should be much easier to find items in the list.
