### ISSUE TITLE
Problems with the billing cycle!

### ISSUE THREAD

**Issue by wedsonlopes** [jeremyvaartjes/subminder#8]
it changes the value of the service we use to pay and sometimes the values we define on the subscription doesn't match the display value .

**Comment by jeremyvaartjes** [comment]
Could you explain this a bit more or go through the steps you take. I need to be able to reproduce this so that I can see what is going on. Thanks!

**Comment by wedsonlopes** [comment]
The problems stopped! It turn out that the value of the billing was changed with out my intervention.
